<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Material3.Avalonia.Demo\Material3.Avalonia.Demo.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
      <PackageReference Include="Avalonia.Wayland" Version="12.1.1" />
      <PackageReference Include="ReactiveUI.Avalonia" Version="12.1.1" />
    </ItemGroup>

</Project>
