<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia" Version="12.1.2" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport"
                          Version="2.2.3"
                          Condition="'$(Configuration)' == 'Debug'" />
      <PackageReference Include="ReactiveUI" Version="24.2.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Models\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Material3.Avalonia\Material3.Avalonia.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Assets\avatar_24.png" />
      <AvaloniaResource Include="Assets\avatar_24.png" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\TextBoxes.axaml.cs">
        <DependentUpon>TextBoxes.axaml</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
