<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia" Version="12.1.1" />
      <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
      <PackageReference Include="Avalonia.Diagnostics" Version="11.3.20" />
      <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.9" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Models\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Material3.Avalonia\Material3.Avalonia.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Assets\avatar_24.png" />
      <AvaloniaResource Include="Assets\avatar_24.png" />
    </ItemGroup>

</Project>
