"""Generate the Material Symbols API and pinned build inputs."""
import fontTools
from fontTools.ttLib import TTFont
import tempfile
import urllib.request
import urllib.parse
import hashlib
import json
from pathlib import Path
import shutil
import sys

ROOT = Path(__file__).resolve().parents[1]
manifest = json.loads((ROOT / "third_party/google/material-symbols/upstream.json").read_text())
if fontTools.__version__ != manifest["fontToolsVersion"]:
    raise RuntimeError("Use fontTools " + manifest["fontToolsVersion"] + " for reproducible generation")
cache = tempfile.TemporaryDirectory(prefix="material-symbols-")
source = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(cache.name)
if len(sys.argv) == 1:
    base = "https://raw.githubusercontent.com/google/material-design-icons/" + manifest["revision"] + "/variablefont/"
    for style in manifest["styles"]:
        for extension in ("ttf", "codepoints"):
            filename = "MaterialSymbols" + style + "[FILL,GRAD,opsz,wght]." + extension
            urllib.request.urlretrieve(base + urllib.parse.quote(filename), source / (style + "." + extension))
for name, digest in manifest["sha256"].items():
    if hashlib.sha256((source / name).read_bytes()).hexdigest() != digest:
        raise ValueError(f"Upstream checksum mismatch: {name}")

def identifier(name):
    result = "".join(part[:1].upper() + part[1:] for part in name.split("_"))
    return "Icon" + result if result[0].isdigit() else result

catalog = dict(line.split() for line in (source / "Outlined.codepoints").read_text().splitlines())
canonical = {}
identifiers = {}
for name, codepoint in sorted(catalog.items(), key=lambda item: (-item[0].count("_"), item[0])):
    key = identifier(name).casefold()
    if key in identifiers:
        previous = identifiers[key]
        if catalog[previous] != codepoint:
            raise ValueError(f"Case-insensitive identifier collision: {previous}, {name}")
        canonical[name] = previous
    else:
        identifiers[key] = name
        canonical[name] = name
names = [name for name in catalog if canonical[name] == name]
for style in manifest["styles"]:
    other = dict(line.split() for line in (source / f"{style}.codepoints").read_text().splitlines())
    if other != catalog:
        raise ValueError(f"Style codepoints differ: {style}")
    font = TTFont(str(source / f"{style}.ttf"))
    axes = {a.axisTag: (a.minValue, a.maxValue) for a in font["fvar"].axes}
    if axes != {"FILL": (0, 1), "GRAD": (-50, 200), "opsz": (20, 48), "wght": (100, 700)}:
        raise ValueError(f"Unexpected axes: {axes}")
    font.close()
    shutil.copyfile(source / f"{style}.ttf", ROOT / f"third_party/google/material-symbols/fonts/{style}.ttf")

header = "// <auto-generated />\nnamespace Material3.Avalonia.Symbols;\n\n"
entries = "\n".join(f"    /// <summary>The {n} symbol.</summary>\n    {identifier(n)} = 0x{v}," for n, v in catalog.items() if canonical[n] == n)
(ROOT / "Material3.Avalonia/Symbols/MaterialSymbol.g.cs").write_text(header + "/// <summary>Material Symbols from the pinned Google catalog.</summary>\npublic enum MaterialSymbol\n{\n" + entries + "\n}\n")
entries = "\n".join(f'        new(MaterialSymbol.{identifier(canonical[n])}, "{n}"),' for n in catalog)
(ROOT / "Material3.Avalonia/Symbols/SymbolCatalog.g.cs").write_text(header + '/// <summary>Searchable names and identities of all available symbols.</summary>\npublic static class SymbolCatalog\n{\n    /// <summary>Gets the complete upstream catalog, including aliases.</summary>\n    public static IReadOnlyList<SymbolEntry> All { get; } = Array.AsReadOnly(new SymbolEntry[]\n    {\n' + entries + '\n    });\n}\n')
entries = "\n".join(f"{identifier(n)}\t{catalog[n]}" for n in names)
(ROOT / "third_party/google/material-symbols/catalog.tsv").write_text(entries + "\n")
